{% set name = "ocifs" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ocifs-{{ version }}.tar.gz
  sha256: 7eed5e046d60ef07c89890df1eedbe95682c87359c9aae9a81a02122f1ae496a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fsspec >=0.8.7
    - oci >=2.43.1
    - python >=3.6

test:
  imports:
    - ocifs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oracle/ocifs
  summary: Convenient filesystem interface over Oracle Cloud's Object Storage
  license: UPL-1.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ahosler
